zb: Require a specific version of env_logger
It is a bad idea to specify `*` as required version and crates.io
doesn't let us publish either if we do:

```
   Uploading zbus v2.0.0-beta.4 (/home/zeenix/checkout/dbus/zbus/zbus)
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error: wildcard (`*`) dependency constraints are not allowed on crates.io. See https://doc.rust-lang.org/cargo/faq.html#can-libraries-use--as-a-version-for-their-dependencies for more information
```