🚨 zb: drop invalid cfg from documentation example
Since commit cf35fbd4f040c7082431780c465cbaeda02581d2, the condition is
inverted. The initial bug seems to have vanished.

---- zbus/src/connection/mod.rs - connection::Connection::executor (line 838) stdout ----
error: unexpected `cfg` condition value: `unix`
  --> zbus/src/connection/mod.rs:842:11
   |
10 | #[cfg(not(target_os = "unix"))]
   |           ^^^^^^^^^^^^^^^^^^