🚨 zx: Pass &[Interface] instead of &[&Interface]
```rust
error: this expression creates a reference which is immediately dereferenced by the compiler
  --> zbus_xmlgen/src/main.rs:82:15
   |
82 |             &[&interface],
   |               ^^^^^^^^^^ help: change this to: `interface`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
   = note: `-D clippy::needless-borrow` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::needless_borrow)]`
```