🚨 zb: Impl Display instead of ToString for MatchRule
Clippy explains the reasons:

```rust
error: direct implementation of `ToString`
   --> zbus/src/match_rule/mod.rs:326:1
    |
326 | / impl ToString for MatchRule<'_> {
327 | |     fn to_string(&self) -> String {
328 | |         let mut s = String::new();
329 | |
...   |
369 | |     }
370 | | }
    | |_^
    |
    = help: prefer implementing `Display` instead
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_trait_impl
    = note: `-D clippy::to-string-trait-impl` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::to_string_trait_impl)]`
```