📝 zb: Drop unneeded explicit link target
Otherwise rustdoc gives an warning:

```
    --> zbus/src/fdo.rs:115:20
    |
115 | /// [ObjectServer](crate::ObjectServer).
    |      ------------  ^^^^^^^^^^^^^^^^^^^ explicit target is redundant
    |      |
    |      because label contains path that resolves to same destination
    |
    = note: when a link's destination is not specified,
            the label is used to resolve intra-doc links
    = note: `-D rustdoc::redundant-explicit-links` implied by `-D warnings`
help: remove explicit link target
    |
115 | /// [ObjectServer].
    |     ~~~~~~~~~~~~~~

error: could not document `zbus`
```