zb/tests: fix random failuring after DestroyObj call
The test randomly fails with:
thread 'async-std/runtime' panicked at 'assertion failed: my_obj_proxy.introspect().await.is_err()', zbus/src/object_server.rs:1001:9

Since the methods are handled asynchronously, we need to wait for the
object "manager" to finish removing the object, before calling a method
on it that is expected to fail.

Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>