🚨 zm,internal: Impl Display instead of ToString
Clippy explains the reasons:

```rust
error: direct implementation of `ToString`
  --> zbus_macros/src/utils.rs:67:1
   |
67 | / impl ToString for PropertyEmitsChangedSignal {
68 | |     fn to_string(&self) -> String {
69 | |         let emits_changed_signal = match self {
70 | |             PropertyEmitsChangedSignal::True => "true",
...  |
76 | |     }
77 | | }
   | |_^
   |
   = help: prefer implementing `Display` instead
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_trait_impl
   = note: `-D clippy::to-string-trait-impl` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::to_string_trait_impl)]`
```