🚩 zb: Disable UDS support on Windows for tokio
Since tokio currently [does not support Unix domain sockets on
Windows][tuds], there is no reason to enable UDS support on Windows+tokio.
This also fixes a build warning against rust nightly:

```rust
error: field `0` is never read
  --> zbus\src\connection\builder.rs:45:16
   |
45 |     UnixStream(UnixStream),
   |     ---------- ^^^^^^^^^^
   |     |
   |     field in this variant
   |
   = note: `-D dead-code` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(dead_code)]`
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
   |
45 |     UnixStream(()),
   |                ~~
```

[tuds]: https://github.com/tokio-rs/tokio/issues/2201