zv: Drop signature rewinding business in ser code
Signature rewinding complicates the signature parsing logic so let's
instead create disposable parser clones for each array element (and dict
key and value) serialization.

This change not only simplifies the serializer logic a bit but also gets
rid of the first error we encounter when serializing a dict with >1
entries for GVariant format (issue#99):

```
panicked at 'calledResult::unwrap()on anErrvalue: Message("invalid type: characters, expected s, g, oorv")'
```

However, we get a different error still later when deserializing this
value:

```
panicked at 'called `Result::unwrap()` on an `Err` value: Message("invalid value: character `e`, expected nul byte expected at the end of strings")'
```

Given that we've tested the deserializer very thoroughly against OStree
data, most likely this is caused by incorrect serialization.