✅ zb: don't expect guid in vsock address
guid is not handled yet. Fix cargo test --features=vsock.

thread 'address::tests::stringify_dbus_addresses' panicked at 'assertion failed: `(left == right)`
  left: `"vsock:cid=98,port=2934"`,
 right: `"vsock:cid=98,port=2934,guid=123"`', zbus/src/address.rs:984:9